version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://postgres:password@db:5432/miniudb?sslmode=disable
      - JWT_SECRET=your_jwt_secret
      - APP_ENV=development
      - REDIS_URL=redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND=http://backend:8080
    depends_on:
      backend:
        condition: service_started

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=miniudb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./backend/db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:password@db:5432/miniudb?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:
