// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID             int32            `json:"id"`
	UserID         pgtype.Int4      `json:"user_id"`
	OriginalUrl    string           `json:"original_url"`
	ShortUrlPrefix string           `json:"short_url_prefix"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
